[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "custom_sdk"
version = "0.0.3"
description = "Custom plugings for Apache Airflow 3."
readme = "README.md"
authors = [
    {name="Sunil Kunchoor", email="sunilkunchoor@gmail.com"},
]

requires-python = ">=3.10"

dependencies = [
    "apache-airflow==3.2.1rc1",
    "apache-airflow-providers-databricks",
    "apache-airflow[statsd]",
]

[project.entry-points."airflow.plugins"]
databricks_custom = "custom_sdk.databricks.plugins:DatabricksCustomPlugin"
bash_custom = "custom_sdk.bash.plugins.google_search_return:OperatorExtraLinkPlugin"